### ISSUE TITLE
Octoprint destroyed

### ISSUE THREAD

**Issue by AlexFeedOrFeed** [cp2004/OctoPrint-OneDriveFileSync#10] opened 2023-01-08 23:20 UTC
Installed, restarted. When I pressed "add account", octoprint froze and never came back. Thanks ;)

I have octoprint installed with docker on latest raspbian os 64-bit.

**Comment by cp2004** [comment] 2023-01-09 14:40
Please, if you have a problem to report, fill in the [bug report form](https://github.com/cp2004/OctoPrint-OneDriveFileSync/issues/new/choose). I can't do anything with an issue report that has no details in it. I need a log file, I need a detailed description of what went wrong, and hopefully some description of what you have tried to do to fix the issue. I need information to be able to reproduce any potential issue before I can fix it.

**Comment by cp2004** [comment] 2023-01-24 14:02
Since there has been no reply, or extra information, I can't investigate the issue. If you still need help you can still comment, but I'll close this issue.

**Closed as not planned by cp2004** 2023-01-24 14:02 UTC
